spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: blog
    show-sql: true

logging:
  level:
    root: info
    com.jdai: debug
  file: /log/blog-dev.log
